version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: lingualint-backend
    networks:
      - lingualint-net
    environment:
      FLASK_ENV: development
      SECRET_KEY: ${SECRET_KEY}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      FRONTEND_URL: ${APP_URL}
      APP_URL: ${APP_URL}
      WEBHOOK_SECRET: ${WEBHOOK_SECRET}
      PORT: 5000
    volumes:
      - ./backend/data:/app/data
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/lingualist
    container_name: lingualint-frontend
    depends_on:
      - backend
    networks:
      - lingualint-net
    ports:
      - "80:80"
    volumes:
      - ./frontend/lingualist/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

networks:
  lingualint-net:
    driver: bridge